version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username_postgresql
      POSTGRES_PASSWORD: password_postgresql
      POSTGRES_DB: database_postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
